Site search engine is now a self-contained part of the site,
...running in an Elasticsearch container that is proxied by nginx.

Site is indexed during CI process.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,12 +5,15 @@ before_script:
   
 build_test:
   script: |
+    # put info about this commit/branch into /info.txt
     echo Information > info.txt
     echo "Branch: ${CI_COMMIT_BRANCH}" >> info.txt
     echo "Commit: ${CI_COMMIT_SHA}" >> info.txt
     echo "Commit comment:" >> info.txt
     echo " ${CI_COMMIT_MESSAGE}" >> info.txt
     echo "Build time: $(date)" >> info.txt
+
+    # get markdown pages for easybuild modules
     rm -rf easybuild-life-sciences-main main.zip ./_scicomputing/bio-modules-18.04.md.orig
     # faster than cloning:
     curl -LO https://github.com/FredHutch/easybuild-life-sciences/archive/refs/heads/main.zip
@@ -28,8 +31,34 @@ build_test:
     tail -n +$FIRST_BLANK_LINE ./_scicomputing/bio-modules-18.04.md.orig >> ./_scicomputing/bio-modules-18.04.md
     rm -rf easybuild-life-sciences-main main.zip ./_scicomputing/bio-modules-18.04.md.orig
 
-
+    # build image
     docker build -t dockerimages.fhcrc.org/wiki:latest .
+
+    # build search index
+    # run image and copy HTML files out of it
+    docker run -d --name wiki -p dockerimages.fhcrc.org/wiki:latest
+    rm -rf tmp && mkdir tmp
+    docker cp wiki:/usr/share/nginx/html/ ./tmp/
+    docker rm -f wiki
+    docker pull elasticsearch:8.4.0
+    docker network create wiki-indexer || true
+    # run an instance of elasticsearch
+    docker run --network wiki-indexer -d --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" -e "xpack.security.enabled=false" elasticsearch:8.4.0
+    sleep 20
+    # create sciwiki0 index
+    curl -X PUT "http://localhost:9200/sciwiki0/" -H 'Content-Type: application/json'
+    # index wiki pages
+    docker build -t indexer -elasticsearch/
+    # run indexer script
+    docker run --network wiki-indexer -d --rm --name indexer -v $(pwd)/tmp:/html indexer
+    # save elasticsearch image (with indexed docs) 
+    docker commit indexer dockerimages.fhcrc.org/wiki_elasticsearch:latest
+    # clean up
+    docker rm -f indexer elasticsearch
+    rm -rf tmp
+
+
+
 
 
 # build for every branch EXCEPT main and push to preview site
@@ -46,7 +75,9 @@ deploy_preview:
   script:
     - docker login --username $DOCKERIMAGES_USER --password $DOCKERIMAGES_PASS https://dockerimages.fhcrc.org
     - docker tag dockerimages.fhcrc.org/wiki:latest dockerimages.fhcrc.org/wiki-preview:latest 
+    - docker tag dockerimages.fhcrc.org/wiki_elasticsearch:latest dockerimages.fhcrc.org/wiki_elasticsearch-preview:latest
     - docker push dockerimages.fhcrc.org/wiki-preview:latest
+    - docker push dockerimages.fhcrc.org/wiki_elasticsearch-preview:latest
     - sleep 15
     - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $PREVIEW_RANCHERAPI_KEY --secret-key $PREVIEW_RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack wiki_preview --file docker-compose-preview.yml --rancher-file rancher-compose.yml
 
@@ -59,6 +90,7 @@ deploy:
     refs:
        - main
   script: |
+    # find orphan assets
     rm -f orphans.txt*
     for F in $(find assets/* -type f) ; do grep -r -q $F * || echo "$F"; done > orphans.txt.tmp
     #cat orphans.txt.tmp | fgrep -v "assets/css/" | fgrep -v "assets/js/" > orphans.txt
@@ -90,6 +122,7 @@ deploy:
     fi
     docker login --username $DOCKERIMAGES_USER --password $DOCKERIMAGES_PASS https://dockerimages.fhcrc.org
     docker push dockerimages.fhcrc.org/wiki:latest
+    docker push dockerimages.fhcrc.org/wiki_elasticsearch:latest
     sleep 15
     rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack wiki --file docker-compose.yml --rancher-file rancher-compose.yml
   
